# -*- coding: utf-8 -*-
"""GATE_Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkFLBJmnoHmJIHIJZcXfmxHAkKkoAN_g
"""

import math
import cmath
import numpy as np
import matplotlib.pyplot as plt


n=np.linspace(-8, 8, num=17)
h2_n=np.eye(1,17,10)
h1_n=np.eye(1,17,9)
h_n=np.eye(1,17,11)
#plot
print(h1_n)

plt.stem(n,h1_n[0],use_line_collection=True)
plt.title('h_1[n]')
plt.xlabel('$n$')
plt.ylabel('$h_1(n)$')
plt.grid()# minor

plt.stem(n,h2_n[0],use_line_collection=True)
plt.title('h_2[n]')
plt.xlabel('$n$')
plt.ylabel('$h_2(n)$')
plt.grid()

plt.stem(n,h_n[0],use_line_collection=True)
plt.title('h[n]')
plt.xlabel('$n$')
plt.ylabel('$h(n)$')
plt.grid()

cascade = np.convolve(h1_n[0],h2_n[0])
#Plotting step response

print(cascade)