# -*- coding: utf-8 -*-
"""GATE_Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkFLBJmnoHmJIHIJZcXfmxHAkKkoAN_g
"""

import math
import cmath
import numpy as np
import matplotlib.pyplot as plt


h1_n=[0,1,0]
h2_n=[0,0,1]
#plot
print(h1_n)
n=[0,1,2]
plt.stem(n,h1_n,use_line_collection=True)
plt.title('h_1[n]')
plt.xlabel('$n$')
plt.ylabel('$h_1(n)$')
plt.grid()# minor

plt.stem(n,h2_n,use_line_collection=True)
plt.title('h_2[n]')
plt.xlabel('$n$')
plt.ylabel('$h_2(n)$')
plt.grid()

cascade = np.convolve(h1_n,h2_n)
#Plotting step response

print(cascade)
## the lower limits change to N1+M1 while upper limits change to N2+M2
ran=list(range(2*n[-1]+1))
plt.stem(ran,cascade,use_line_collection=True)
plt.title('h[n]')
plt.xlabel('$n$')
plt.ylabel('$h(n)$')
plt.grid()