# -*- coding: utf-8 -*-
"""GATE_Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RYdnFOnxJlB21N0AYY6oTbhqHTJOSRs
"""

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [-1,-1, 1]

plt.step(x, y)
plt.show()

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [0,0, 1]

plt.step(x, y)
plt.title('u(t)')
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.show()

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [1,1, 0]

plt.step(x, y)
plt.title('u(-t)')
plt.xlabel('$t$')
plt.ylabel('$u(-t)$')
plt.show()

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [-1,-1, 0]

plt.step(x, y)
plt.title('-u(-t)')
plt.xlabel('$t$')
plt.ylabel('$-u(-t)$')
plt.show()

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [-1/2,-1/2, 1/2]
plt.title('odd part of u(t)')
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.step(x, y)
plt.show()

import matplotlib.pyplot as plt

x = [-5,0,5] 
y = [1/2,1/2, 1/2]
plt.title('even part of u(t)')
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.step(x, y)
plt.show()